#!/usr/bin/env node
// Builds the icon bundle: the Iconify data for exactly the icons the site uses,
// written to lib/icon-bundle.js for lib/icons.ts to register. Its type lives in
// the hand-written lib/icon-bundle.d.ts, so type-checking never needs it.
//
// next.config.mjs and vitest.config.mts run this when they load, so every
// build, dev server and test run starts from a bundle that matches the source.
// A name the installed icon sets do not have is an error, which fails the
// build rather than shipping an empty box.
//
//   pnpm icons
//
// Icon names are found by scanning the source as text, the way
// scripts/check-links.mjs reads the dataset: the script stays a plain
// `node scripts/build-icons.mjs` with no TypeScript loader. Every name the site
// uses is a string literal of the form 'prefix:name', where the prefix is one
// of the installed @iconify-json packages.

import {
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { getIcons } from '@iconify/utils';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = join(ROOT, 'lib', 'icon-bundle.js');
const SOURCE_DIRS = ['app', 'components', 'constants', 'hooks', 'lib'];
const ICON_SET_PACKAGE = '@iconify-json/';

const require = createRequire(import.meta.url);

/** The prefix of every icon set installed as an @iconify-json package. */
function installedPrefixes() {
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  return Object.keys({ ...pkg.dependencies, ...pkg.devDependencies })
    .filter((name) => name.startsWith(ICON_SET_PACKAGE))
    .map((name) => name.slice(ICON_SET_PACKAGE.length));
}

function loadIconSet(prefix) {
  try {
    const path = require.resolve(`${ICON_SET_PACKAGE}${prefix}/icons.json`);
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

function sourceFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return sourceFiles(path);
    return /\.tsx?$/.test(entry.name) && !/\.test\.tsx?$/.test(entry.name)
      ? [path]
      : [];
  });
}

/** Every icon name quoted anywhere in the site's source, sorted. */
export function collectIconNames() {
  const prefixes = installedPrefixes().map((prefix) =>
    prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  );
  const pattern = new RegExp(
    `['"]((?:${prefixes.join('|')}):[a-z0-9]+(?:-[a-z0-9]+)*)['"]`,
    'g'
  );

  const names = new Set();
  for (const dir of SOURCE_DIRS) {
    for (const file of sourceFiles(join(ROOT, dir))) {
      for (const match of readFileSync(file, 'utf8').matchAll(pattern)) {
        names.add(match[1]);
      }
    }
  }
  return [...names].sort();
}

/**
 * The Iconify data for the given icon names, one subset per icon set. Throws,
 * naming every icon it could not find, if any name is missing from the
 * installed sets.
 */
export function buildIconBundle(names = collectIconNames()) {
  const byPrefix = new Map();
  for (const name of names) {
    const [prefix, icon] = name.split(':');
    byPrefix.set(prefix, [...(byPrefix.get(prefix) ?? []), icon]);
  }

  const bundle = [];
  const missing = [];
  for (const [prefix, icons] of byPrefix) {
    const set = loadIconSet(prefix);
    const subset = set && getIcons(set, icons, true);
    const notFound = subset ? (subset.not_found ?? []) : icons;

    missing.push(...notFound.map((icon) => `${prefix}:${icon}`));
    if (subset && Object.keys(subset.icons).length > 0) {
      delete subset.not_found;
      bundle.push(subset);
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `No icon data for ${missing.join(', ')}. Each name must exist in an ` +
        'installed @iconify-json set; browse them at ' +
        'https://icon-sets.iconify.design'
    );
  }
  return bundle;
}

/** Writes the bundle, leaving the file untouched when nothing changed. */
export function writeIconBundle() {
  const source =
    '// Generated by scripts/build-icons.mjs on every build, dev start and\n' +
    '// test run. Do not edit: change the icon names in the source instead.\n' +
    `export default ${JSON.stringify(buildIconBundle())};\n`;

  if (!existsSync(OUTPUT) || readFileSync(OUTPUT, 'utf8') !== source) {
    writeFileSync(OUTPUT, source);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeIconBundle();
}
